from setuptools import find_packages, setup

setup(
    name='directory_sso_api_client',
    version='7.2.3',
    url='https://github.com/uktrade/directory-sso-api-client',
    license='MIT',
    author='Department for International Trade',
    description='Python API client for Export Directory.',
    packages=find_packages(exclude=["tests.*", "tests"]),
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    include_package_data=True,
    install_requires=[
        'directory_client_core>=7.2.5,<=8.0.0',
    ],
    extras_require={
        'test': [
            'django>=2.2.10,<=4.2.3',
            'black==23.1.0',
            'flake8==3.8.4',
            'isort==5.6.4',
            'pytest-cov',
            'pytest-django>=3.8.0,<4.0.0',
            'pytest-sugar>=0.9.2,<1.0.0',
            'pytest==5.3.5',
            'pytest-codecov',
            'GitPython',
            'requests>=2.22.0,<3.0.0',
            'requests_mock==1.7.0',
            'setuptools>=45.2.0,<50.0.0',
            'twine>=3.1.1,<4.0.0',
            'wheel>=0.34.2,<1.0.0',
        ]
    },
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.2',
        'Framework :: Django :: 4.2',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.9',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
