from setuptools import find_packages, setup

setup(
    name='directory_sso_api_client',
    version='7.3.5',
    url='https://github.com/uktrade/directory-sso-api-client',
    license='MIT',
    author='Department for International Trade',
    description='Python API client for Export Directory.',
    packages=find_packages(exclude=["tests.*", "tests"]),
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    include_package_data=True,
    install_requires=[
        'directory_client_core>=7.2.12,<=8.0.0',
    ],
    extras_require={
        'test': [
            'django>=4.2.10,<5.0',
            'black==23.1.0',
            'flake8',
            'isort==5.6.4',
            'pytest-cov',
            'pytest-django>=3.8.0,<4.11.1',
            'pytest-sugar>=0.9.2,<1.0.0',
            'pytest==8.4.2',
            'pytest-codecov',
            'GitPython',
            'requests>=2.22.0,<3.0.0',
            'requests_mock==1.7.0',
            'setuptools',
            'twine',
            'wheel>=0.34.2,<1.0.0',
        ]
    },
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.2',
        'Framework :: Django :: 4.2',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.13',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
